spring:
  cloud:
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080

    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: user_route
          uri: lb://seed-pro-user
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*),/user/$\{segment}


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

  ## 前端项目，/api
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree

server:
  port: 88
